version: "3"

services:
  node:
    build: ./docker/node
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./web:/node
    working_dir: /node
    environment:
      - HOGE=${HOGE}
      - NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=${NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - NEXT_PUBLIC_STRIPE_PRODUCT_KEY=${NEXT_PUBLIC_STRIPE_PRODUCT_KEY}

networks:
  defaults:
